### ISSUE TITLE
Which license would fit the project the best?

### ISSUE THREAD

**Issue by openscript** [ictorg/competency-framework#2]
What is a good license for this project? In my opinion it should fit the following requirements:
- Free and open as possible
- Reusable by everyone

Should it become the single point of truth? Do we need to prevent companies to use it commercially?

**Comment by diegosteiner** [comment]
Maybe a CC-licence suits?

https://choosealicense.com/licenses/cc-by-sa-4.0/

**Comment by openscript** [comment]
Probably this is a good choice!

**Comment by openscript** [comment]
License applied.
